Fix surface swi simulations
amanzi/ats pull request #128
Opened 2022-04-20 21:27 UTC by dasvyat

New evaluator for surface water content

2022-04-27 13:25 UTC, ecoon commented
@dasvyat I'm not sure I understand this PR.  Why are there all these extra commits that I made months and months ago?  Many of them look like they're already in ats-1.2; are they not in master?

2022-04-27 14:03 UTC, ecoon requested changes
Ok, so it looks like the only "real" change here is the new evaluator?  Can you just make only that change on konstantin/state and do a new PR?

2022-05-06 18:56 UTC, dasvyat commented on .github/workflows/ats-ci.yml
> +        ref:        amanzi-1.2
I didn't make this change it probably appeared due to merging

2022-05-06 19:09 UTC, dasvyat commented on src/pks/flow/constitutive_relations/water_content/overland_pressure_unfrozen_water_content_evaluator.cc
> +  Evaluator for determining height( rho, head )
Ethan, we discussed this issue a bit before. That was the name that we decided to use. In the previous version "surface_water_content_evaluator" you didn't use density and scaled by molar mass. It worked correctly for ice water case, but it is wrong for the salt case. We conclude that this one will not work for frozen case, so I called unfrozen_water_content

2022-06-25 02:31 UTC, ecoon commented
closing this in favor of new, clean PR

2022-06-25 02:31 UTC, closed without merging